name: Ejecucion

on: push

jobs:
  hola_mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar codigo
        uses: actions/checkout@v5

      - name: descargar pytest
        run: pip install pytest

      - name: correr pytest
        run: pytest test.py
